### ISSUE TITLE
Prototype how to display docked entities on GUI

### ISSUE THREAD

**Issue by vbence86** [vbence86/fivenations#175]
As a developer,
I'd like to have a design prototype that shows how the queue of docked entities should be displayed on the GUI panel
so that it can be implemented in the upcoming sprints.

A/C
- A design prototype shows the state of the panel when a selected entity has docked entities

**Comment by tuardan** [comment]
As a designer,
I made a design prototype that shows the docking and undocking methods. 
You can find it at the url below:
https://youtu.be/DrPrJIj_tcs

**Comment by vbence86** [comment]
Well done @tuardan
