### ISSUE TITLE
Update vision property of federation entities

### ISSUE THREAD

**Issue by vbence86** [vbence86/fivenations#310]
## Intent
Since Fog of War has been integrated to the gameplay, the `vision` attribute of the entities has become obsolete. We need to update these values according to the new range.

## User Story
As a project owner,
I'd like to amend the `vision` attribute of the federation entities
so that they would reveal the tiles according to the new built-in masks associated with the new vision ranges.

## Acceptance Criteria
- Federation entities have their `vision` attributes set in a predefined range (1-20).

**Comment by tuardan** [comment]
As a desinger I updated the vision property of federation entities
