### ISSUE TITLE
Menu assets

### ISSUE THREAD

**Issue by vbence86** [vbence86/fivenations#425]
## Prelude
The current version of Five Nations does not have any Menu and therefore appears less professional for potential players.

## User story
As a Developer
I'd like to have all the graphics assets for the menu
So that it can be constructed.

## Acceptance Criteria
- All menu assets are bundled into a TP sprite sheet. 

## Notes
The Menu should end up looking like this:
![765390-starcraft-ii-wings-of-liberty-windows-screenshot-main-menu](https://user-images.githubusercontent.com/6104164/36449948-b11ce77c-168c-11e8-9bd1-73390178cb75.jpg)

**Comment by tuardan** [comment]
As a designer I've finished with the artworks.
[Mainmenu.zip](https://github.com/vbence86/fivenations/files/1834884/Mainmenu.zip)
