### ISSUE TITLE
Amend Small Silicon Asteroid Spritesheet

### ISSUE THREAD

**Issue by vbence86** [vbence86/fivenations#471]
## Prelude
`asteroid_silicon_sm_02.png` spritesheet appears to contain an undesired frame that breaks the pre-defined idle animation. 

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/6104164/39350518-b25de92e-49fe-11e8-9802-151291ef0e51.gif)

## Expected
similarly to `asteroid_silicon_sm01.png` it should take in only two icons.

![asteroid_silicon_sm01](https://user-images.githubusercontent.com/6104164/39350594-ec104a54-49fe-11e8-8175-4671f3e36e7f.png)

## Actual
It shows 3 icons.
![asteroid_silicon_sm02](https://user-images.githubusercontent.com/6104164/39350595-ec29ee8c-49fe-11e8-9dea-5adec255bcae.png)

**Comment by tuardan** [comment]
As a designer I corrected the silicon asteroid 02.
