### ISSUE TITLE
Generate spritesheets for background ornaments

### ISSUE THREAD

**Issue by vbence86** [vbence86/fivenations#48]
As a developer,
I'd like to have example assets for background ornaments to start off with
So that the integration of background items can be kicked off as described in #47 (*Add background ornaments to the map*) story.

A/C
- To have an example item for static ornament
- To have an example item for animating ornament
- The generated spritesheets are outputed from TexturePacker along with the related Atlas files (JSON).
- The foregoing resources are shared in Slack.

**Comment by tuardan** [comment]
I'm ready with the needed graphics, I'll send them via wetransfer because of the file size
