### ISSUE TITLE
Add "Ship/Deliver Cargo" icon to control button icons

### ISSUE THREAD

**Issue by vbence86** [vbence86/fivenations#609]
## Prelude
`icarus` entities now have to wait until the "parent" `miningstation` entities have at least 250 resources in total until the `Entity.Delivery` activity is executed. This gives no control to the user when and how frequently the resources can be collected at the `commandstation`.

## User story
As a Project Owner
I'd like to provide a control button to the user to manually trigger delivery of resources accumulated in the `miningstation` entities
So that User do not necessarily have to wait until the cargo of the attached `icarus` is full up.

## Acceptance Criteria
- Ship/Deliver Cargo icon is added to the GUI.png spritesheet
- Atlas file is updated accordingly

**Comment by tuardan** [comment]
As a designer I make a control button graphics. The user can manually trigger delivery of resources accumulated in the miningstation entities by clicking on it.
