### ISSUE TITLE
Invalid Building icons order 

### ISSUE THREAD

**Issue by vbence86** [vbence86/fivenations#679]
## Expected
Building icons on Construction panel appear in a predefined order based on the building category:
- Supplimetary
- Manufactory
- Research
- Military

## Actual
Building icons appear in an alphabetical order

## Notes
The order is defined by `construction` attribute in `src/assets/datas/units/fed/engineershuttle.json` as follows:

```
"construction": [
    "astrometricstation",
    "civilianbase",
    "defenseplatform",
    "defensesatellite",
    "dockyard",
    "fleetheadquarters",
    "fusionreactor",
    "merchantport",
    "miningstation",
    "researchcenter",
    "shipfactory",
    "solarstation"
  ],
```

**Comment by tuardan** [comment]
As a designer I changed the order of the Building icons.
